# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Augflow < Formula
  desc "Local-first Developer Productivity Tool"
  homepage "https://github.com/deptz/augflow"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deptz/augflow-releases/releases/download/v0.0.6/augflow_0.0.6_darwin_amd64.tar.gz"
      sha256 "755d2d67f734add958ed427890da106da7ca8dc3b4a298377d210ca66fac58f8"

      define_method(:install) do
        bin.install "augflow"
        if File.directory?("web/dist")
          (share/"augflow").install "web"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deptz/augflow-releases/releases/download/v0.0.6/augflow_0.0.6_darwin_arm64.tar.gz"
      sha256 "be8efe2e7e39d7d860fbf2189454386bd957b9637964b629545c8c323b31523f"

      define_method(:install) do
        bin.install "augflow"
        if File.directory?("web/dist")
          (share/"augflow").install "web"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deptz/augflow-releases/releases/download/v0.0.6/augflow_0.0.6_linux_amd64.tar.gz"
      sha256 "e384890fe70f70ca8d90dbd748ff20421ef934980854921a664e92907419572f"
      define_method(:install) do
        bin.install "augflow"
        if File.directory?("web/dist")
          (share/"augflow").install "web"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deptz/augflow-releases/releases/download/v0.0.6/augflow_0.0.6_linux_arm64.tar.gz"
      sha256 "d698cb6d3835df860a915213b911f96a8878dc9f3e94fd1a772ff9e7348fe76a"
      define_method(:install) do
        bin.install "augflow"
        if File.directory?("web/dist")
          (share/"augflow").install "web"
        end
      end
    end
  end

  test do
    system "#{bin}/augflow", "--version"
  end
end
