# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Augflow < Formula
  desc "Local-first Developer Productivity Tool"
  homepage "https://github.com/deptz/augflow"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deptz/augflow-releases/releases/download/v0.1.5/augflow_0.1.5_darwin_amd64.tar.gz"
      sha256 "97ea48dc12c1375f5a20ff6b4c949d8a12e182a6ef485009fabecd9f08e4ad44"

      define_method(:install) do
        bin.install "augflow"
        if File.directory?("web/dist")
          (share/"augflow").install "web"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deptz/augflow-releases/releases/download/v0.1.5/augflow_0.1.5_darwin_arm64.tar.gz"
      sha256 "62e28669f15a94ae65c0de7c75b70ecefc122722f006cb7594aae8547a6c6515"

      define_method(:install) do
        bin.install "augflow"
        if File.directory?("web/dist")
          (share/"augflow").install "web"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deptz/augflow-releases/releases/download/v0.1.5/augflow_0.1.5_linux_amd64.tar.gz"
      sha256 "de2072e0fd270e21d0738e8c280067443fb511b22df4d313fe343f6323e26d77"
      define_method(:install) do
        bin.install "augflow"
        if File.directory?("web/dist")
          (share/"augflow").install "web"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deptz/augflow-releases/releases/download/v0.1.5/augflow_0.1.5_linux_arm64.tar.gz"
      sha256 "5a0571106b845ce81d11d672bac12399886044d5498be07aeeafb0e240fdc9f9"
      define_method(:install) do
        bin.install "augflow"
        if File.directory?("web/dist")
          (share/"augflow").install "web"
        end
      end
    end
  end

  test do
    system "#{bin}/augflow", "--version"
  end
end
