# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Augflow < Formula
  desc "Local-first Developer Productivity Tool"
  homepage "https://github.com/deptz/augflow"
  version "0.0.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deptz/augflow-releases/releases/download/v0.0.16/augflow_0.0.16_darwin_amd64.tar.gz"
      sha256 "ac359cade19624e1c716ab843b63c1ef84108437c71b0cb8b5bea519fad48d24"

      define_method(:install) do
        bin.install "augflow"
        if File.directory?("web/dist")
          (share/"augflow").install "web"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deptz/augflow-releases/releases/download/v0.0.16/augflow_0.0.16_darwin_arm64.tar.gz"
      sha256 "6460f9c7d9f0c24f128901993cc6d79c99ef70abcbf0191e0b941dacf6942731"

      define_method(:install) do
        bin.install "augflow"
        if File.directory?("web/dist")
          (share/"augflow").install "web"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deptz/augflow-releases/releases/download/v0.0.16/augflow_0.0.16_linux_amd64.tar.gz"
      sha256 "a5af36fa9d1a659589182e8b42ebf7276fd9d4bdf8ccbe60fd6f3994a11fe517"
      define_method(:install) do
        bin.install "augflow"
        if File.directory?("web/dist")
          (share/"augflow").install "web"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deptz/augflow-releases/releases/download/v0.0.16/augflow_0.0.16_linux_arm64.tar.gz"
      sha256 "e42cca4f195808370346f62d6a70fc47e5a1ecd5e1380b75e3758c303959ed32"
      define_method(:install) do
        bin.install "augflow"
        if File.directory?("web/dist")
          (share/"augflow").install "web"
        end
      end
    end
  end

  test do
    system "#{bin}/augflow", "--version"
  end
end
