# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MkrAiReady < Formula
  desc "Validate AI environment readiness across supported stacks"
  homepage "https://github.com/deptz/mkr-ai-ready-releases"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deptz/mkr-ai-ready-releases/releases/download/v0.0.2/mkr-ai-ready_0.0.2_darwin_amd64.tar.gz"
      sha256 "99425fd6e994f334995d31e202d8f11f71cc0e85b703b2e1791527896e681d05"

      define_method(:install) do
        bin.install "mkr-ai-ready"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deptz/mkr-ai-ready-releases/releases/download/v0.0.2/mkr-ai-ready_0.0.2_darwin_arm64.tar.gz"
      sha256 "02ca3cd6b4da2485d2a5db87d7b710adaa156b7dd76192b57b200779beaee6dd"

      define_method(:install) do
        bin.install "mkr-ai-ready"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deptz/mkr-ai-ready-releases/releases/download/v0.0.2/mkr-ai-ready_0.0.2_linux_amd64.tar.gz"
      sha256 "ea7dffede74a0ac5b187518017049c74035e78fe39f77f069c35220a93850a36"
      define_method(:install) do
        bin.install "mkr-ai-ready"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deptz/mkr-ai-ready-releases/releases/download/v0.0.2/mkr-ai-ready_0.0.2_linux_arm64.tar.gz"
      sha256 "1f22d688126a57f6c743c8d2482bd8d215c9215b994fb592dc503622617715e8"
      define_method(:install) do
        bin.install "mkr-ai-ready"
      end
    end
  end

  test do
    system "#{bin}/mkr-ai-ready", "--version"
  end
end
