# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MkrAiReady < Formula
  desc "Validate AI environment readiness across supported stacks"
  homepage "https://github.com/deptz/mkr-ai-ready-releases"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deptz/mkr-ai-ready-releases/releases/download/v0.0.1/mkr-ai-ready_0.0.1_darwin_amd64.tar.gz"
      sha256 "4c96e1afdfb21b3b7e41a9dd15045feb74e5c7258f95835a6598436868487db6"

      define_method(:install) do
        bin.install "mkr-ai-ready"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deptz/mkr-ai-ready-releases/releases/download/v0.0.1/mkr-ai-ready_0.0.1_darwin_arm64.tar.gz"
      sha256 "24deaaf8c0931f5c32a975cea7ee29ea08ee22d58617915afa3cb420e26a127a"

      define_method(:install) do
        bin.install "mkr-ai-ready"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deptz/mkr-ai-ready-releases/releases/download/v0.0.1/mkr-ai-ready_0.0.1_linux_amd64.tar.gz"
      sha256 "5e6be7bf03baea60021bc27d7cc9cac6a4a3d16b95ea1bf15bd7b25535854f25"
      define_method(:install) do
        bin.install "mkr-ai-ready"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deptz/mkr-ai-ready-releases/releases/download/v0.0.1/mkr-ai-ready_0.0.1_linux_arm64.tar.gz"
      sha256 "9711ce90e5d60b2e1ef39ed79a39bbd9bf6cbe708d592f91a4d97dd40bc8495a"
      define_method(:install) do
        bin.install "mkr-ai-ready"
      end
    end
  end

  test do
    system "#{bin}/mkr-ai-ready", "--version"
  end
end
