# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MkrAiReady < Formula
  desc "Validate AI environment readiness across supported stacks"
  homepage "https://github.com/deptz/mkr-ai-ready-releases"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deptz/mkr-ai-ready-releases/releases/download/v0.0.1/mkr-ai-ready_0.0.1_darwin_amd64.tar.gz"
      sha256 "bfe543fc9b1c3be40a3eb154c4690c124d2bb027f0eb10a430972e9164ce957f"

      define_method(:install) do
        bin.install "mkr-ai-ready"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deptz/mkr-ai-ready-releases/releases/download/v0.0.1/mkr-ai-ready_0.0.1_darwin_arm64.tar.gz"
      sha256 "d892361efc3b6f2e709d6b0325f16be9c93b41daa8cc5e97663598df63832b54"

      define_method(:install) do
        bin.install "mkr-ai-ready"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deptz/mkr-ai-ready-releases/releases/download/v0.0.1/mkr-ai-ready_0.0.1_linux_amd64.tar.gz"
      sha256 "ad7f17111dcd4498f79ee7459e6008496f02fad920158d316f35c3c0e703f4c4"
      define_method(:install) do
        bin.install "mkr-ai-ready"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deptz/mkr-ai-ready-releases/releases/download/v0.0.1/mkr-ai-ready_0.0.1_linux_arm64.tar.gz"
      sha256 "6727389720d32d56ac2bc8a957e4b9c1a35d36be680ea126710272a2b5a85009"
      define_method(:install) do
        bin.install "mkr-ai-ready"
      end
    end
  end

  test do
    system "#{bin}/mkr-ai-ready", "--version"
  end
end
